languageCode: "en-us"
title: "SLC is"
theme: "hugo-simplecss"

params:
  description: "Sharpest corner of the IPFS."

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "posts/"
      weight: 2
    - name: Music
      url: "music/"
      weight: 3
    - name: About
      url: "about/"
      weight: 4

permalinks:
  post: "/posts/:slug/"

relativeURLS: true

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
