languageCode: "en-us"
title: "SLC is"
theme: "hugo-simplecss"

params:
  AuthorName: Spencer Churchill
  GitHubUser: splch
  description: "Sharpest corner of the IPFS."

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "posts/"
      weight: 2
    - name: Music
      url: "music/"
      weight: 3
    - name: About
      url: "about/"
      weight: 4

permalinks:
  post: "/posts/:slug/"

relativeURLS: true

markup:
  highlight:
    codeFences: true
    style: tango
  goldmark:
    renderer:
      unsafe: true

related:
  includeNewer: true
  indices:
    - name: tags
      weight: 90
    - name: categories
      weight: 60
    - name: date
      weight: 30
  threshold: 100
  toLower: true

tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 1

summaryLength: 40
hasCJKLanguage: true
