baseurl: "/"
languageCode: "en-us"
title: "SLC is"
theme: "hugo-theme-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles:
  ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/posts/:slug/"

menu:
  main:
    - name: Home
      url: ""
    - name: Posts
      url: "posts/"
    - name: Music
      url: "music/"
    - name: About
      url: "about/"

params:
  description: "Sharpest corner of the IPFS."

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
