name = "SimpleCSS"
license = "MIT"
licenselink = "https://github.com/splch/hugo-simplecss/blob/master/LICENSE"
description = "Use Simplecss with the bare-minimum Hugo theme to optimize readability and expressibility."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/splch/hugo-simplecss/"

# If you have a running demo of the theme.
demosite = "https://slc.is/"

tags = ["blog", "minimal", "personal", "light", "dark", "portfolio", "dark mode"]
features = ["blog", "privacy", "no javascript", "simple"]

# If the theme has a single author
[author]
    name = "Spencer Churchill"
    homepage = "https://slc.is/"
